# Generated by Django 3.1.7 on 2021-05-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal_item', '0004_currentgoalday_currentgoalweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDayTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_is_complete', models.BooleanField(default=False)),
                ('goal_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goal_item.currentgoalweek')),
            ],
        ),
        migrations.CreateModel(
            name='GoalDayThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_is_complete', models.BooleanField(default=False)),
                ('goal_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goal_item.currentgoalweek')),
            ],
        ),
        migrations.CreateModel(
            name='GoalDayOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_is_complete', models.BooleanField(default=False)),
                ('goal_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goal_item.currentgoalweek')),
            ],
        ),
        migrations.CreateModel(
            name='GoalDayFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_is_complete', models.BooleanField(default=False)),
                ('goal_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goal_item.currentgoalweek')),
            ],
        ),
        migrations.CreateModel(
            name='GoalDayFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_is_complete', models.BooleanField(default=False)),
                ('goal_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goal_item.currentgoalweek')),
            ],
        ),
    ]
