# Generated by Django 3.1.7 on 2021-05-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goaldays', '0002_auto_20210524_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaldayone',
            name='gd1_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayone',
            name='gd1_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayone',
            name='gd1_smoothie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayone',
            name='gd1_water',
            field=models.BooleanField(default=False),
        ),
    ]
