# Generated by Django 3.1.7 on 2021-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goaldays', '0003_auto_20210526_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaldayfive',
            name='gd5_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfive',
            name='gd5_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfive',
            name='gd5_smoothie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfive',
            name='gd5_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfour',
            name='gd4_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfour',
            name='gd4_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfour',
            name='gd4_smoothie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldayfour',
            name='gd4_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaythree',
            name='gd3_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaythree',
            name='gd3_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaythree',
            name='gd3_smoothie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaythree',
            name='gd3_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaytwo',
            name='gd2_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaytwo',
            name='gd2_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaytwo',
            name='gd2_smoothie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldaytwo',
            name='gd2_water',
            field=models.BooleanField(default=False),
        ),
    ]
