# Generated by Django 2.2.14 on 2021-04-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalitem',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
