# Generated by Django 3.1.7 on 2021-05-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal_item', '0004_currentgoalday_currentgoalweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgoalweek',
            name='choose_goals',
            field=models.ManyToManyField(blank=True, related_name='choose_goals', to='goal_item.GoalItem'),
        ),
        migrations.CreateModel(
            name='DayOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_is_complete', models.BooleanField(default=False)),
                ('day_one_goals', models.ManyToManyField(blank=True, null=True, to='goal_item.GoalItem')),
                ('goal_week', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goal_week', to='goal_item.currentgoalweek')),
            ],
        ),
    ]
