# Generated by Django 3.1.7 on 2021-05-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_item', '0007_auto_20210526_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgoalweek',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
