# Generated by Django 3.1.7 on 2021-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_item', '0008_auto_20210526_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgoalweek',
            name='gd2_extra_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentgoalweek',
            name='gd3_extra_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentgoalweek',
            name='gd4_extra_point',
            field=models.BooleanField(default=False),
        ),
    ]
