# Generated by Django 3.1.7 on 2021-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_item', '0009_auto_20210527_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgoalweek',
            name='is_active_week',
            field=models.BooleanField(default=False),
        ),
    ]
